site_name: 0Nita - Zites Italiani
pages:
- Introduzione: index.md
- Ziti:
  - TODO: zites/TODO.md
- Forum: forum.md
- Blog:
  - Informatica: blog/informatica.md
  - Tempo Libero: blog/tempolibero.md
- Torrents: torrents.md
- FAQ: faq.md
theme: readthedocs