site_name: 0Nita - Zites Italiani
pages:
- Introduzione: index.md
- Ziti:
  - nessuno ancora: zites/TODO.md
- Forum e chat: forumchat.md
- Blog:
  - Informatica: blog/informatica.md
  - Tempo Libero: blog/tempolibero.md
- Torrents: torrents.md
- FAQ: faq.md
theme: readthedocs